### ISSUE TITLE
An Arethusa extension: Git handling

### ISSUE THREAD

**Issue by LFDM** [alpheios-project/arethusa#583]
Will soon push a branch with a first skeleton of a new main module called `arethusa.extensions`.

The plan is here to provide a set of extensions that can be used by other services/factories - right now I am having `Persisters` in mind.

Through the configuration of the persister you should be able to define extensions - which will automatically do *something* with the data that is going to be persisted.

The first such extension would be a `Git` handler. Of course it couldn't do any real git work (like commits), because this is the responsibility of the server, but it could at least produce a commit message, which includes a summary of all changes made in an annotation session.

(maybe the name `Git` for this extension is already a bad decision - because it would as of now only pad the persisted data with this modification message)

Changes are needed for this to solve this cleanly. The `history` plugin is already producing summaries of changes. The problem is that this is done in a directive and can therefore not be reused. The logic to produce such strings should be placed inside the `StateChange` event object itself. A function placed there needs to do the following things:

- Be able to be called in two modes: with compilation and without.
  - For a commit message we just need a simple string
  - If we want to use this inside of directives we need it to be HTML compliant and compiled.
      - It would therefore need to take an optional scope (the scope of the including directive) or produce a scope of it's own if need be

Once this refactor is done we can start to think how Perseids would eventually deal with this. The local annotation environment would probably try to mimick this API in a simplified way. The local express server would get git powers as well. Right now it already works on a git repository anyway - we would just need to add the power to commit on save. The message handling would be exactly the same as in Perseids then.

More thoughts to come.

**Comment by LFDM** [comment]
One question to think about would be locale handling. Does a backend want localized commit messages? The summary strings would be localized - so if a user annotates in German, would Perseids take a German commit message or override the locale for this message?



One other thought for the extension:
It should open up a modal dialog on save to allow the user to edit the commit message. An optional setting would disable this behavior and always commit with the default save message.

**Comment by balmas** [comment]
referenced branch was never pushed. closing this.
