### ISSUE TITLE
oddities with aT tab

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#658]
Reported by Vanessa Gorman.  Sometimes a word will not move.  If you go back and sentence and return, then it is on the root.  This occurs most often (but not exclusively) when the aT tab is highlighted. Likewise, when the aT tab is highlighted and you have inserted a word, sometimes you cannot select and move the word until you get off the aT tab.

Not yet reproduced.

**Comment by Masoumeh** [comment]
Unfortunately, I cannot reproduce this problem. I don't even understand it from this explanation. @balmas could you please put more information or a screen shot? Or ask Vanessa Gorman to provide more info? Thanks!

**Comment by balmas** [comment]
@vgorman1 can you confirm that this is still a problem and provide a screenshot? I can't recall if this was only occurring on the staging version with the changes from the hackathon or if this is also a problem in the currently live version.  Thanks!

**Comment by vgorman1** [comment]
I have not noticed this in a while, but I will try to reproduce it and get back to you.

Vanessa

Vanessa B. Gorman
Professor and Undergraduate Chair
Department of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by vgorman1** [comment]
I have not had this happen recently, so I would say  it is either from the staging platform or else fixed.

Vanessa B. Gorman
Professor and Undergraduate Chair
Department of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by balmas** [comment]
Ok thanks @vgorman1 . I think it was probably in the staging version. I suspect a bug still lingers in the master branch for this. We need to test again once all of the remaining work from the hackathon is finished.

**Comment by balmas** [comment]
ohhh. I understand the latter problem: "when the aT tab is highlighted and you have inserted a word, sometimes you cannot select and move the word until you get off the aT tab"

This is happening because the insertion point action is responding to the selection in this case.  This is noted in #408 which requests improvements to the aT workflow.

**Comment by balmas** [comment]
I don't know if the first problem, a token not moving, is related to this, but I don't think it's actually a bug related to the hackathon changes but since #408 is long standing, I think probably not.  I'm going to close this.
