### ISSUE TITLE
apply to multiple items broken

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#666]
reported by @vgorman1 on commit 2dc665b:

When I select multiple items and hit APPLY, it doesn’t always give the labels to all.  It may have to do with the Syntax Descriptions, which I just turned on.  On this sentence, I chose three items and tried to label them all as AuxP.  When I hit APPLY, only two labeled correctly and only one got the Syntax Description. I didn’t see this before I turned on the syntax descriptions, but I will turn them off and see if I can replicate it.

**Comment by Masoumeh** [comment]
I cannot reproduce this error. When I select multiple items and change the all labels through change all list and hit Apply, the labels and in tree and Syntax Descriptions all get updated. Am I checking the correct feature?

**Comment by vgorman1** [comment]
Again, this is probably in the staging platform.  I haven’t experienced it since I quit using Staging.

Vanessa B. Gorman
Professor and Undergraduate Chair
Department of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by balmas** [comment]
Yes, but I think @Masoumeh is testing this in the master branch of the code base, which included all of the changes that were in staging at the time.

**Comment by vgorman1** [comment]
Without going into the staging platform, I can only tell you that I haven’t seen this since I shifted back to the main platform.  Once the staging goes live, I am sure I will be able to reproduce it if it still exists.

Best wishes,

Vanessa

Vanessa B. Gorman
Professor and Undergraduate Chair
Department of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by balmas** [comment]
Ok. @Masoumeh just double checking -- did you have the Syntax Descriptions feature enabled when testing this? (i.e. via the settings options on the relations tab)

**Comment by Masoumeh** [comment]
Yes. I enable the feature and then select 3 words. So, the description is shown for each word. I put a label through change all list and hit Apply. The labels in tree and syntax description change regarding the same chosen label. 
(I'm still testing this under the main branch in http://localhost:8081/app/#/staging?doc=1)

**Comment by balmas** [comment]
Ok. Another possibility that seems likely is that it is triggered by some combination of cached user forms and the code.

**Comment by balmas** [comment]
I'm going to label this a "Testing" item for now, we should come back to it to confirm once we're ready to try to deploy a release from the master branch again.

**Comment by balmas** [comment]
confirmed introduced in e15ab9c028db524064f05931dde70e17c4133192

probably related to #667 and possibly also #698 

relation.getLabelObj, called by the syntactical_description directive ,  is throwing an error because the ancestors aren't there for anything but the first selected token

**Comment by balmas** [comment]
Actually not sure if it has anything much to do with the fact that they are batched .. it might be happening when a relation label on a selected word doesn't match the currently loaded tag set.
