### ISSUE TITLE
Case for gerundive and gerund

### ISSUE THREAD

**Issue by gcelano** [alpheios-project/arethusa#679]
My students report that it is not possible to annotate the case for the gerundive and gerund in Latin. I can fix the problem, if I am told which file should be modified

**Comment by balmas** [comment]
the latin attributes file is https://github.com/latin-language-toolkit/arethusa-configs/blob/master/configs/arethusa.morph/lat_attributes.json

**Comment by balmas** [comment]
@gcelano you can test your branch of this now using the gclat format.

**Comment by balmas** [comment]
@gcelano what is the status of this?

**Comment by balmas** [comment]
Per @gcelano Seems to work, Anastasia is testing further

**Comment by balmas** [comment]
@gcelano are we ready to deploy this?

**Comment by gcelano** [comment]
I think so. Anastasia has not reported any error.

**Comment by balmas** [comment]
This is merged to master in 7116d4863c3bde36f16db8457878af0badfb8908

Not yet deployed
