### ISSUE TITLE
change to use - for empty attribute value causes bad results on morphology equivalency check 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#697]
Reported by Polina Yordanova

Caused by #694, specifically the change in 4f53518a8604dfd51b02046cd0b30733d634f909

I'm not sure how many other places in the code are effected by this, but it was found in the sg tab.

The sg.morphHasChanged function is called by sg.checkAndUpdateGrammar to see if the user has changed the morphology since it was last stored in the state.  The problem is that this is always returning true for elements with empty attributes (i.e. '-' in the postag) because when the original sg object is populated, the morph object doesn't get the empty attributes, but the morph object on the token does have them.

I haven't fully isolated exactly where this difference occurs - I think it has some interaction with the browser cache of morphological forms.

This goes back to my original worry mentioned in #694 about the overloading use of specialEmptyAttributes to present the short and long values for newly added forms was not the right thing to do. I couldn't pinpoint my concern then, as we hadn't isolated any occurrences depending upon it other than the concatonated forms display, but apparently this is another bit of code that was relying on the - value producing an empty object (as evidenced by this comment in morph.js: `// attrObj can be undefined when the postag is -`

The question really is what to do now. I think it's not a good thing that there are implicit dependencies on the fact that '-' doesn't produce a short/long value so I am tempted to just address them as we find them like this, but @Masoumeh I'd like to know what you think.

**Comment by balmas** [comment]
I should add that this is also exposing a bug in the SG code because the actual problem that is preventing the proper display of the SG attribute is that the ancestors property is not being carried along when the object is updated after a morph change

**Comment by Masoumeh** [comment]
Actually, I cannot say which decision is the best, since there might be some points in the requirements and also the logic of the source code that I don't know exactly. I would also go for the solution that was chosen before (i.e. using underscore). But if it is decided to omit underscore in the end, I can go through the code to find dependencies and we can make an effort to test the changes for a while.

**Comment by balmas** [comment]
Per discussion with @gcelano and @Masoumeh we will back the fix for #673 out of the production environment for now as a hotfix for this issue. But I'm going to leave it in master so that we can work through the bugs there.
