### ISSUE TITLE
review plugin not refreshing tree upon save?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#709]
Reported by @rgorman

My students and I have noticed that sometimes the compare feature updates for changes with a single click and sometimes we have to go out to the overview page to register the new comparison.  Is this something you would like us to describe more clearly or is it something you’re already well aware of?  Needless to say, the students would like to minimize the number of clicks necessary to check their work as they go along, but I realize that this may be difficult for technical reasons.

**Comment by balmas** [comment]
@rgorman I wonder if this was actually another instance of #711 let me know if it is still happening now.

**Comment by rgorman** [comment]
I don't quite understand your question, but things seem to be working fine.  I will keep testing and let you know what happens.


Bob



________________________________

**Comment by balmas** [comment]
Oh sorry. I just mean that I think maybe the problem was that the changes looked like they weren't taking effect because the bug referenced in #711 was preventing the tree from being fully updated.

**Comment by balmas** [comment]
I think we can assume this is fixed.
