### ISSUE TITLE
Latin gerund does not need Person, Number, Tense, Mood

### ISSUE THREAD

**Issue by nevenjovanovic** [alpheios-project/arethusa#768]
When adding a new form in Arethusa, if this form is a gerund (e. g. faciendo from facio), fields for Person, Number, Tense, and Mood are offered. Gerund is a nominal form, however, and does not have these dimensions; true, in the present implementation they can be filled with blanks (dashes ----), but their existence confuses users unnecessarily and makes the annotation process longer. These fields could be left out from the form for gerund.

**Comment by balmas** [comment]
@TDBuck can you follow up with @gcelano, @rgorman, @vgorman1 and see if all are agreed with making this change to the default aldt tagset? Thanks! (If so, this can move to the arethusa-configs repo as an issue there)

**Comment by gcelano** [comment]
In the current annotation scheme, the gerund is annotated as a mood of the verb. Therefore only Number, Tense, and Person can be deleted.

@TDBuck, I would create another version of the tagset, so that it can be tested before the change becomes definitive. Make also sure that a dash appears in the right places in the xml

**Comment by nevenjovanovic** [comment]
@gcelano -- my (interlingual) mistake, I was thinking about omitting from the form Voice, not Mood; Mood should, of course, be kept. If I'm correct, the gerund cannot be passive, so we would only have active or deponens as values for Voice, if we don't want to confuse the annotators.

**Comment by gcelano** [comment]
Since we can distinguish between active and deponent verbs (for the gerund), I would keep this distinction. But deleting the "passive" option here makes sense.

**Comment by nevenjovanovic** [comment]
@gcelano, I agree, you're right! Best, Neven

**Comment by balmas** [comment]
@TDBuck can you go ahead and move this item to arethusa-configs and make the change in a test tagset as @gcelano suggests?  Thanks!

**Comment by balmas** [comment]
closing this, as it's being handled via arethusa-configs issue
