### ISSUE TITLE
Widget: tree sizing issues

### ISSUE THREAD

**Issue by monzug** [alpheios-project/arethusa#815]
go to latin author Ovid in text env and select Metamorphoses. double click on mutatas (first sentence) and open the related diagram. the fonts are huge. see screenshot
![Screen Shot 2020-06-15 at 2 39 20 PM](https://user-images.githubusercontent.com/41396793/84662297-eccc2100-af1b-11ea-9d9b-985351ce3d72.png)

**Comment by balmas** [comment]
Additional requestion from @rgorman:

is it possible to make the Alpheios/Perseids combo work properly when adjusting display "zoom"?

Often, when using the trees, etc. in a classroom, this means projecting the computer display onto a big screen.  In these cases, the display image is often too small for most students to read.  But if we re-size it via the browser controls, various navigation buttons and the like are pushed off the screen.  

I imagine it is a lot of work to keep things in a good layout when the size is not 100%.  If this is not possible incrementally, perhaps a "projection mode" could be considered, where all elements were sized for, say, display = 150% or the like?

**Comment by balmas** [comment]
The first issue, with the zoom of the narrow trees, is fixed and deployed in https://github.com/perseids-tools/arethusa-widget/releases/tag/v2.1.0 which is now live at trees.alpheios.net.  The fix can be verified with https://texts.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/1.1-1.30

I could not reproduce the other zooming problems so far.

**Comment by monzug** [comment]
diagram looks good. tested in Chrome and Firefox  (PC).

**Comment by balmas** [comment]
I need to follow up with Bob still about the other issue. I'll enter it as a new issue if it needs to be resolved though.
