### ISSUE TITLE
option to exclude unusedSelector and unusedHighlighter from display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#816]
in a read-only widget view, the unusedSelector and unusedHighlighter don't really add any value. It would be nice to be able to optionally remove these from the display

**Comment by balmas** [comment]
This is fixed and deployed in https://github.com/perseids-tools/arethusa-widget/releases/tag/v2.1.0 which is now live at trees.alpheios.net. The fix can be verified with any of the treebanked texts at texts.alpheios.net

**Comment by balmas** [comment]
this apparently caused the problems in #820 so reopening for another look

**Comment by balmas** [comment]
To retest with  #820

**Comment by balmas** [comment]
this is fixed now but need to wait for alpheios-project/alpheios-core#523 to be fixed to test in texts-test.

**Comment by balmas** [comment]
test in texts-test.alpheios.net

Alpheios Embedded Library 3.3.0-qa.20200813461
Alpheios Components 3.3.0-qa.20200813570 


Please test with a variety of panel sizes and tree sizes.

**Comment by monzug** [comment]
looks good to me

**Comment by monzug** [comment]
Chrome/Mac
![Screen Shot 2020-08-14 at 4 25 19 PM](https://user-images.githubusercontent.com/41396793/90259750-d58daf00-de4a-11ea-921d-8c670a0f2811.png)
![Screen Shot 2020-08-14 at 4 25 03 PM](https://user-images.githubusercontent.com/41396793/90259758-d7f00900-de4a-11ea-9099-e961fd0c2c14.png)

**Comment by balmas** [comment]
hmm. that's interesting. Can you clear your cache and try again just to be sure?

I was able to reproduce with the prior version of the code but cannot now (in Chrome on Linux).

In any event, I think I can live with it. What about you?

**Comment by monzug** [comment]
I clear my cache before opening the texts site. I'll do it again (unless
there is again a problem with having the extension open on a tab)

**Comment by monzug** [comment]
it's still a little off but we can leave as is

**Comment by monzug** [comment]
![new-alpheios-treebank](https://user-images.githubusercontent.com/41396793/90263936-597d7200-de1e-11ea-924d-d27d88fa56a2.JPG)
