### ISSUE TITLE
Tree overflow with dep_tree_no_selector template.

### ISSUE THREAD

**Issue by zfletch** [alpheios-project/arethusa#820]
This looks like a bug introduced in https://github.com/alpheios-project/arethusa/pull/818

When the `depTree` template is `js/templates/dep_tree_no_selector.html`, the tree bounds checking doesn't work and the tree can overflow on the bottom up to around 25px. There is also an extra gap at the top. (It also looks like there's a 1 or 2 pixel overflow in the `dep_tree.html` template. I think this is worth fixing, but it's a much smaller issue and isn't really noticeable unless zoomed in).

---

No selector (bottom):

<img width="991" alt="dep_tree_no_selector" src="https://user-images.githubusercontent.com/3039310/88304959-eaa57100-ccd6-11ea-9c27-d340d518e7eb.png">

---

No selector (top):

<img width="980" alt="dep_tree_no_selector_top" src="https://user-images.githubusercontent.com/3039310/88305304-52f45280-ccd7-11ea-8351-b189d2de4b87.png">

---

Selector:

<img width="993" alt="dep_tree" src="https://user-images.githubusercontent.com/3039310/88304995-f6913300-ccd6-11ea-8cb2-b516380f29ac.png">

**Comment by balmas** [comment]
oh shoot sorry about that. I will take a look as soon as I can. In the meantime, feel free to revert back to the other template.
