### ISSUE TITLE
tiny tree after resizing 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#821]
in Chrome/PC,  when enlarging the panel, sometimes I loose the pop-up (the mouse goes outside the panel area and I loose the focus on the pop-up so it closes). when I reopen the pop-up and the related diagram, the size is much smaller than regular diagram size. This is not reproducible in FF or Chrome/Mac. see screenshot
![diagram-resizing-panel](https://user-images.githubusercontent.com/41396793/89794081-90891600-daf4-11ea-8580-d3a12391a8d2.JPG)

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios-core/issues/507#issuecomment-671390933_

**Comment by balmas** [comment]
@monzug can you try a little to see if you can reproduce this with the test page at https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/test.html ? 

I have been able to reproduce it fairly easily at texts-test.alpheios.net but not at all so far in the misc-dev test page, so I'm wondering if it's somehow caused by something in the underlying page css.

**Comment by monzug** [comment]
did you try on Chrome/PC? could not repro on Chrome/Mac.

**Comment by balmas** [comment]
Yes, Chrome/Linux actually.  Could reproduce it almost every time with the panel on the right and resizing it beyond the max. both popup and panel close and then when I reopen it is tiny until resized again.

**Comment by monzug** [comment]
I cannot reproduce at
https://alpheios-misc-dev.s3.us-east-2.amazonaws.com/treebank-test-page/test.html

**Comment by balmas** [comment]
I think I'm going to let it go. It seems to me to be mostly an edge case and its easily resolved by resizing the panel again. I suspect it's a timing issue related to the drawing of the display.

**Comment by monzug** [comment]
ok
