### ISSUE TITLE
Morphology check box is out of focus in Firefox

### ISSUE THREAD

**Issue by zfletch** [alpheios-project/arethusa#823]
Bug originally reported by @monzug in https://github.com/perseids-publications/treebank-template/issues/55

The check box in the `morph` tab of the sidebar is out of focus on Firefox (the issue is more noticeable on FF for Windows, but it happens with FF on other platforms to a lesser extent).

It looks like the issue is caused by a [CSS transform](https://github.com/alpheios-project/arethusa/commit/a00f260086c5a6213a98e6df16e0e4d51e3a9437) (`-moz-transform: scale(1.6);`) combined with an issue in Firefox where check boxes don't scale correctly. (Possibly tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1448682) or [here](https://bugzilla.mozilla.org/show_bug.cgi?id=400364)). The reason that the transform is there in the first place is because  Firefox doesn't render the checkbox as large as other browsers do given the styling `width: 1.3rem; height: 1.3rem;`.

![90265092-12907c00-de20-11ea-8840-05a326eca28c](https://user-images.githubusercontent.com/3039310/90776601-4bb96800-e2c8-11ea-8f72-e44db735951f.jpg)

**Comment by balmas** [comment]
I think we won't fix this here. The display of morph is handled differently in the react viewer.
