### ISSUE TITLE
ability to open a tree focused on a specific subsection

### ISSUE THREAD

**Issue by balmas** [alpheios-project/arethusa#825]
related to #824 , requested by @rgorman

"(#824)  would be a great feature especially if we could “pre-set” which parts of a tree would be expanded or collapsed. These days I am teaching my students how to work their way through a complex sentence one clause at a time (or at least one sub-tree at a time). To do this I have to pull sub-trees from trees by hand, which is slow and tedious work.

In order for the commentary that I provide to make sense (very necessary in this day of covid and distance learning), the trees must open in the shape I want them to.  That is, the proper sub-tree must be isolated.
 
As I start to think about it, I imagine this might be trickier than just having expand and contract buttons on nodes.  My approach would probably mean that sometimes selected downstream nodes would remain expanded while upstream nodes would be collapsed. A hard problem maybe?"

**Comment by balmas** [comment]
@zfletch are you going to implement this in the react viewer? If so, I think I would not do it here.

**Comment by zfletch** [comment]
I am planning on implementing it in the React viewer. I don't have a timeline but I don't think it will be too difficult.

I've created an issue here: https://github.com/perseids-tools/treebank-react/issues/21

**Comment by balmas** [comment]
closing this. It won't be fixed in Arethusa but in the new viewer app.
